const hotels = [
  {
    name: 'Hotel Sunrise',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXOar24Du37yshw7pkDT7em2LO1Slhj50krg&s',
    description: 'A beautiful sunrise view hotel.',
    fullDescription: 'Located on the beachfront, Hotel Sunrise offers breathtaking views and luxurious amenities. Enjoy our world-class services and relax in our beautifully designed rooms.',
    bookLink: 'https://example.com/book-hotel-sunrise',
  },
  {
    name: 'Mountain Retreat',
    image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/99/bd/f6/hillwood-hotel-resort.jpg?w=600&h=400&s=1',
    description: 'A serene mountain getaway.',
    fullDescription: 'Nestled in the mountains, Mountain Retreat is your perfect escape from the hustle and bustle of city life. Experience tranquility and enjoy our cozy accommodations and warm hospitality.',
    bookLink: 'https://example.com/book-mountain-retreat',
  },
  {
    name: 'Antu Hill Homestay',
    image: 'https://antucottage.com/wp-content/uploads/2022/07/7.jpg',
    description: 'Enjoy breathtaking sunrise views from Antu Hill.',
    fullDescription: 'Located at the top of Antu Danda, this homestay offers panoramic views of the mountains and valleys. Experience local hospitality and enjoy traditional meals in a peaceful environment.',
    bookLink: 'https://example.com/book-antu-hill-homestay',
  },
  {
    name: 'Suryodaya Homestay',
    image: 'https://booking-manager-api-hop-nepal.s3.eu-west-1.amazonaws.com/4859/conversions/shreeantu-670x350.jpg',
    description: 'Experience tea gardens and serene landscapes.',
    fullDescription: 'Suryodaya Homestay provides an authentic Nepali homestay experience with a view of lush tea gardens. Enjoy the tranquility and interact with friendly locals.',
    bookLink: 'https://example.com/book-suryodaya-homestay',
  },
  {
    name: 'Shree Antu Homestay',
    image: 'https://www.hotelmechicrown.com/storage/experiences/shree-antu-visit/main/thumbs/medium_1647777260.webp',
    description: 'Perfect for nature lovers and adventurers.',
    fullDescription: 'Shree Antu Homestay is a great choice for those looking to explore the beauty of Antu Danda. With comfortable accommodations and close proximity to hiking trails, it’s a perfect retreat.',
    bookLink: 'https://example.com/book-shree-antu-homestay',
  },
  {
    name: 'Peaceful Homestay',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuNnR_M7ZuiRawy77wA0kjvGK-k5JrArG2z065wguZJz-viCWwdiK3yLaA2swbTaIEar8&usqp=CAU',
    description: 'A quiet retreat amidst nature.',
    fullDescription: 'Peaceful Homestay lives up to its name, offering a serene environment perfect for relaxation. Wake up to the sound of birds and breathe in the fresh mountain air.',
    bookLink: 'https://example.com/book-peaceful-homestay',
  },
  {
    name: 'Sunset View Homestay',
    image: 'https://nepalish.com/wp-content/uploads/2022/08/Sunrise-from-antu.jpg',
    description: 'Stunning sunset views right from your room.',
    fullDescription: 'Located on the western slope of Antu Danda, this homestay is famous for its mesmerizing sunset views. It offers cozy rooms and delicious local cuisine, making it ideal for a relaxing stay.',
    bookLink: 'https://example.com/book-sunset-view-homestay',
  },
  {
    name: 'Antu Tea Garden Homestay',
    image: 'https://eternalhimalaya.com/uploads/img/antu-danda-banner-image.jpg',
    description: 'Stay near lush tea gardens.',
    fullDescription: 'Antu Tea Garden Homestay is perfect for those who love tea and nature. Surrounded by beautiful tea gardens, this homestay offers a unique opportunity to experience the local tea culture and lifestyle.',
    bookLink: 'https://example.com/book-antu-tea-garden-homestay',
  },
  {
    name: 'Sano Pathivara Homestay',
    image: 'https://www.pigeontravels.com/wp-content/uploads/2019/03/ilam-pic.jpg',
    description: 'A spiritual and peaceful experience.',
    fullDescription: 'Sano Pathivara Homestay is located near the famous Pathivara temple and offers a spiritual atmosphere with modern comforts. Perfect for travelers seeking peace and quiet in a sacred environment.',
    bookLink: 'https://example.com/book-sano-pathivara-homestay',
  },
  {
    name: 'Evergreen Homestay',
    image: 'https://www.communityhomestay.com/blog/wp-content/uploads/2022/03/cottage-at-sriantu.jpg',
    description: 'Experience a refreshing stay surrounded by nature.',
    fullDescription: 'Evergreen Homestay is located in the heart of Antu Danda, surrounded by green forests and scenic views. It is ideal for those looking to reconnect with nature.',
    bookLink: 'https://example.com/book-evergreen-homestay',
  },
  {
    name: 'Himalayan Horizon Homestay',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/421831233.jpg?k=78626bb803ddd72db5e6c8dc9c8c28d399d1f3bc2a56ed9795ce51372e7246fb&o=&hp=1',
    description: 'A cozy homestay with mountain views.',
    fullDescription: 'Himalayan Horizon Homestay offers a stunning view of the Himalayan range. Enjoy the comfort of a home-like atmosphere while taking in the natural beauty of the mountains.',
    bookLink: 'https://example.com/book-himalayan-horizon-homestay',
  },
  {
    name: 'Tea House Homestay',
    image: 'https://www.communityhomestay.com/blog/wp-content/uploads/2017/07/Antu-Homestay-.jpg',
    description: 'A traditional homestay near the tea plantations.',
    fullDescription: 'Tea House Homestay provides an immersive experience of the local tea culture. Located next to sprawling tea estates, it’s a perfect place for tea enthusiasts to explore and enjoy.',
    bookLink: 'https://example.com/book-tea-house-homestay',
  },
  {
    name: 'Pinewood Homestay',
    image: 'https://www.homestaying.in/cropped_images/hotel_image_1-1690010879.png',
    description: 'A peaceful retreat among pine forests.',
    fullDescription: 'Pinewood Homestay is nestled among pine trees, offering a serene and refreshing environment. The cool breeze and pine scent make it a perfect place for relaxation.',
    bookLink: 'https://example.com/book-pinewood-homestay',
  },
  {
    name: 'Antu View Homestay',
    image: 'https://pbs.twimg.com/media/EI6L6CcUYAY5mfz.jpg',
    description: 'A homestay with spectacular views of Antu Danda.',
    fullDescription: 'Antu View Homestay offers panoramic views of the Antu Danda region, perfect for those who love scenic landscapes. Enjoy the calm environment and beautiful sunrise from your room.',
    bookLink: 'https://example.com/book-antu-view-homestay',
  },
  {
    name: 'Sunrise Dream Homestay',
    image: 'https://s3.ap-south-1.amazonaws.com/chsfiles/media/CBWPcgxYhPcq7n4cEjBJDb3k1glfeXPSZezMpmBZ.jpeg',
    description: 'Witness the perfect sunrise from your window.',
    fullDescription: 'Sunrise Dream Homestay allows you to witness the magical sunrise over the hills from your room. It’s an ideal spot for photographers and nature lovers.',
    bookLink: 'https://example.com/book-sunrise-dream-homestay',
  },
  {
    name: 'Nature Bliss Homestay',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/340466239.jpg?k=b3303064885188a2ffd11e0dac5a35f07337431c48e1af317b736a94deed7d5b&o=&hp=1',
    description: 'Stay amidst the beauty of nature.',
    fullDescription: 'Nature Bliss Homestay offers a calming retreat in the midst of nature. Enjoy trekking, bird watching, and the quiet solitude of the forests surrounding the homestay.',
    bookLink: 'https://example.com/book-nature-bliss-homestay',
  },
  {
    name: 'Valley View Homestay',
    image: 'https://s3.ap-south-1.amazonaws.com/chsfiles/media/95ryc2vUK9OBPQLv0g7y90jW7qJlkE8Uv6EkS3Tx.jpeg',
    description: 'A perfect place for valley views and nature trails.',
    fullDescription: 'Valley View Homestay offers stunning views of the valley below. Explore nearby trails and enjoy a peaceful stay in this charming homestay.',
    bookLink: 'https://example.com/book-valley-view-homestay',
  },
  {
    name: 'Cultural Heritage Homestay',
    image: 'https://old.risingnepaldaily.com/photos/1/giriraj/House.JPG',
    description: 'An experience rich in local culture and tradition.',
    fullDescription: 'Cultural Heritage Homestay gives you an authentic taste of local Nepali culture. Participate in traditional activities, enjoy local cuisine, and immerse yourself in the heritage of the area.',
    bookLink: 'https://example.com/book-cultural-heritage-homestay',
  },
  {
    name: 'Serene Stay Homestay',
    image: 'https://nepalish.com/wp-content/uploads/2022/08/hotels-antu.jpg',
    description: 'A peaceful escape in a beautiful landscape.',
    fullDescription: 'Serene Stay Homestay provides a relaxing environment surrounded by hills and greenery. It’s perfect for those looking to escape the city and reconnect with nature.',
    bookLink: 'https://example.com/book-serene-stay-homestay',
  },
  {
    name: 'Bamboo Grove Homestay',
    image: 'https://thekkady.org/wp-content/uploads/2016/06/bamboo-grove.jpg',
    description: 'Unique stay experience surrounded by bamboo groves.',
    fullDescription: 'Bamboo Grove Homestay is an eco-friendly retreat surrounded by bamboo forests. Experience sustainable living while enjoying the beauty and tranquility of the bamboo groves.',
    bookLink: 'https://example.com/book-bamboo-grove-homestay',
  },
  {
    name: 'Hilltop Haven Homestay',
    image: 'https://r2imghtlak.mmtcdn.com/r2-mmt-htl-image/htl-imgs/202207280034305618-13ffe0aa0dc411edaeee0a58a9feac02.jpg',
    description: 'A haven on top of the hills.',
    fullDescription: 'Hilltop Haven Homestay offers amazing views and a tranquil environment at the peak of Antu Danda. It’s a great place to unwind and enjoy nature.',
    bookLink: 'https://example.com/book-hilltop-haven-homestay',
  },
];

export default hotels;